"""
levels_data.py - data for all 15 levels of Chroma Lie.

Every level is a plain dict so new levels can be added without touching code.

"tiles" is an ASCII map, 30 columns x 20 rows, each cell = 32x32 px:
    .  empty                 #  neutral block (always safe, solid)
    R  red tile (solid)      B  blue tile (solid)     P  purple tile (solid)
    M  motion tile: safe only while you keep moving
    L  late-trap tile: looks blue, collapses into spikes shortly after being touched
    J  spring pad            ^  spikes (always deadly)
    S  player start          E  exit gate (always safe)
Whether R/B/P kill you depends on the CURRENT rule (see deception.py).

Other fields (pixel coordinates):
    moving_obstacles : oscillator (rect, axis, distance, period, phase) or
                       orbit (center, radius, count, speed rad/s, size) - always deadly
    timed_traps      : laser rect that is ON for `on` seconds every `period` seconds
    moving_platforms : rect that eases back and forth to `to`
    rule_change      : list of events {trigger: zone|time, method: silent|glitch|vague_message,
                       changes: {...}, display: optional new (possibly lying) instruction text}
    cycle            : (level 14) rule shuffles through `states` every `period` seconds
"""

LEVELS = [
    {
        "id": 1,
        "title": "HONEST START",
        "concept": "Honest tutorial: plain colored tiles, the rule is true. Learn to move and jump.",
        "instruction": "RED = DANGER   BLUE = SAFE",
        "player_start": [2, 17],
        "exit_gate": [26, 17],
        "tiles": [
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#.................BB.........#",
            "#.........BBB................#",
            "#............................#",
            "#.S.......................E..#",
            "######RRR####RRRR####RRR######",
            "##############################",
        ],
        "initial_rules": {},
        "moving_obstacles": [],
        "timed_traps": [],
        "moving_platforms": [],
        "rule_change": [],
    },
    {
        "id": 2,
        "title": "FIRST DOUBT",
        "concept": "Narrow path squeezed between red and blue: honest rule, no room to hesitate.",
        "instruction": "RED = DANGER   BLUE = SAFE",
        "player_start": [1, 17],
        "exit_gate": [27, 9],
        "tiles": [
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#..........................E.#",
            "#........................#####",
            "#............................#",
            "#....................BB......#",
            "#............................#",
            "#........................BB..#",
            "#RRRRRRRRRRRRRRRR............#",
            "#....................BB......#",
            "#S...........................#",
            "#BBBBBBBBBBBBBBBBBBRRRRRRRRRR#",
            "##############################",
        ],
        "initial_rules": {},
        "moving_obstacles": [],
        "timed_traps": [],
        "moving_platforms": [],
        "rule_change": [],
    },
    {
        "id": 3,
        "title": "MOVING PARTS",
        "concept": "Moving hazards that ignore color. Timing matters now.",
        "instruction": "RED = DANGER   BLUE = SAFE",
        "player_start": [2, 17],
        "exit_gate": [27, 17],
        "tiles": [
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#.S........................E.#",
            "#########RR######RRRRRRR######",
            "##############################",
        ],
        "initial_rules": {},
        "moving_obstacles": [{"type": "oscillator",
              "rect": [420, 352, 24, 96],
              "axis": "y",
              "distance": 128,
              "period": 2.2,
              "phase": 0.0},
             {"type": "oscillator",
              "rect": [804, 352, 24, 96],
              "axis": "y",
              "distance": 128,
              "period": 2.2,
              "phase": 0.5}],
        "moving_platforms": [{"rect": [544, 528, 80, 16], "to": [688, 528], "period": 3.2}],
        "timed_traps": [],
        "rule_change": [],
    },
    {
        "id": 4,
        "title": "THE FIRST LIE",
        "concept": "Mid-level the color meanings swap silently. The text does not update.",
        "instruction": "RED = DANGER   BLUE = SAFE",
        "player_start": [2, 17],
        "exit_gate": [27, 17],
        "tiles": [
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#..............BBB....BBB....#",
            "#............................#",
            "#.S........................E.#",
            "#BBBBBRRBBBB##RRRRRRRRRRRRR###",
            "##############################",
        ],
        "initial_rules": {},
        "rule_change": [{"trigger": {"type": "zone", "rect": [384, 0, 64, 640]},
              "method": "silent",
              "changes": {"red_meaning": "safe", "blue_meaning": "danger"}}],
        "moving_obstacles": [],
        "timed_traps": [],
        "moving_platforms": [],
    },
    {
        "id": 5,
        "title": "A FLICKER OF TRUTH",
        "concept": "A 0.3s glitch on the instruction text warns you right before the swap.",
        "instruction": "RED = DANGER   BLUE = SAFE",
        "player_start": [2, 17],
        "exit_gate": [26, 5],
        "tiles": [
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#.........................E..#",
            "#......................#######",
            "#............................#",
            "#...................RR.......#",
            "#............................#",
            "#................RR..........#",
            "#............................#",
            "#.............##.............#",
            "#............................#",
            "#..........BB................#",
            "#............................#",
            "#.......BB...................#",
            "#.S..........................#",
            "#######......................#",
            "#######......................#",
        ],
        "initial_rules": {},
        "rule_change": [{"trigger": {"type": "zone", "rect": [448, 288, 64, 96]},
              "method": "glitch",
              "pre_glitch": 0.3,
              "changes": {"red_meaning": "safe", "blue_meaning": "danger"}}],
        "moving_obstacles": [],
        "timed_traps": [],
        "moving_platforms": [],
    },
    {
        "id": 6,
        "title": "TICK, TOCK",
        "concept": "Timed laser traps pulse every 2 seconds, warning blink first. Colors stay honest.",
        "instruction": "RED = DANGER   BLUE = SAFE",
        "player_start": [1, 17],
        "exit_gate": [27, 17],
        "tiles": [
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#...........BBB..............#",
            "#............................#",
            "#S.........................E.#",
            "#####RRR####RRR####RRR########",
            "##############################",
        ],
        "initial_rules": {},
        "timed_traps": [{"rect": [298, 96, 12, 480], "period": 2.0, "on": 1.0, "offset": 0.0},
             {"rect": [522, 96, 12, 480], "period": 2.0, "on": 1.0, "offset": 0.66},
             {"rect": [746, 96, 12, 480], "period": 2.0, "on": 1.0, "offset": 1.33},
             {"rect": [810, 96, 12, 480], "period": 2.0, "on": 1.0, "offset": 0.33}],
        "moving_obstacles": [],
        "moving_platforms": [],
        "rule_change": [],
    },
    {
        "id": 7,
        "title": "WRONG WAY",
        "concept": "Left and right silently invert. Colors remain honest.",
        "instruction": "RED = DANGER   BLUE = SAFE",
        "player_start": [2, 17],
        "exit_gate": [27, 13],
        "tiles": [
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#..........................E.#",
            "#........................#####",
            "#....................BB......#",
            "#................BB..........#",
            "#.S..R.......................#",
            "#BBBBBBBBB######RRRRRRRRRRRRR#",
            "##############################",
        ],
        "initial_rules": {},
        "rule_change": [{"trigger": {"type": "zone", "rect": [384, 0, 64, 640]},
              "method": "silent",
              "changes": {"controls_swapped": True}}],
        "moving_obstacles": [],
        "timed_traps": [],
        "moving_platforms": [],
    },
    {
        "id": 8,
        "title": "DOUBLE LIE",
        "concept": "Color swap and inverted controls, at the same moment, in silence.",
        "instruction": "RED = DANGER   BLUE = SAFE",
        "player_start": [2, 17],
        "exit_gate": [27, 12],
        "tiles": [
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#..........................E.#",
            "#.........................####",
            "#..................RR........#",
            "#......................RR....#",
            "#...............RR...........#",
            "#.S..........................#",
            "#BBBBBBBBB#####BBBBBBBBBBBBBB#",
            "##############################",
        ],
        "initial_rules": {},
        "rule_change": [{"trigger": {"type": "zone", "rect": [352, 0, 64, 640]},
              "method": "silent",
              "changes": {"red_meaning": "safe", "blue_meaning": "danger", "controls_swapped": True}}],
        "moving_obstacles": [],
        "timed_traps": [],
        "moving_platforms": [],
    },
    {
        "id": 9,
        "title": "UNLISTED",
        "concept": "A third color the instructions never mention. Is purple safe? Find out.",
        "instruction": "RED = DANGER   BLUE = SAFE",
        "player_start": [2, 17],
        "exit_gate": [26, 12],
        "tiles": [
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#.........................E..#",
            "#......................#######",
            "#.................PPP........#",
            "#............PPP.............#",
            "#.......PPP..................#",
            "#.S..........................#",
            "######RRRRRRRRRRRRRRRRRRRRRRR#",
            "##############################",
        ],
        "initial_rules": {},
        "moving_obstacles": [{"type": "orbit",
              "center": [528, 384],
              "radius": 62,
              "count": 2,
              "speed": 1.7,
              "size": 10}],
        "timed_traps": [],
        "moving_platforms": [],
        "rule_change": [],
    },
    {
        "id": 10,
        "title": "KEEP MOVING",
        "concept": "Chevron tiles are only safe while you keep moving. Stand still and they bite.",
        "instruction": "RED = DANGER   BLUE = SAFE",
        "player_start": [1, 17],
        "exit_gate": [28, 17],
        "tiles": [
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#S..........................E#",
            "####MMMMMMM##MMMMMMMM##MMMM###",
            "##############################",
        ],
        "initial_rules": {},
        "moving_obstacles": [{"type": "oscillator",
              "rect": [516, 352, 24, 96],
              "axis": "y",
              "distance": 128,
              "period": 2.4,
              "phase": 0.0},
             {"type": "oscillator",
              "rect": [788, 352, 24, 96],
              "axis": "y",
              "distance": 128,
              "period": 2.4,
              "phase": 0.35}],
        "timed_traps": [],
        "moving_platforms": [],
        "rule_change": [],
    },
    {
        "id": 11,
        "title": "THE TEXT LIES",
        "concept": "The instruction flips to RED = SAFE. Reality does not change.",
        "instruction": "RED = DANGER   BLUE = SAFE",
        "player_start": [2, 17],
        "exit_gate": [27, 11],
        "tiles": [
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#..........................E.#",
            "#........................#####",
            "#.................BB.........#",
            "#.........BB..........BB.....#",
            "#.............BB.............#",
            "#......BB....................#",
            "#.S..........................#",
            "######RRRRRRRRRRRRRRRRRRRRRRR#",
            "##############################",
        ],
        "initial_rules": {},
        "rule_change": [{"trigger": {"type": "zone", "rect": [160, 0, 64, 640]},
              "method": "glitch",
              "changes": {},
              "display": "RED = SAFE   BLUE = DANGER",
              "flicker_truth": True}],
        "moving_obstacles": [],
        "timed_traps": [],
        "moving_platforms": [],
    },
    {
        "id": 12,
        "title": "EVERYTHING AT ONCE",
        "concept": "Colors, moving hazards and timed traps together, with two rule swaps.",
        "instruction": "RED = DANGER   BLUE = SAFE",
        "player_start": [2, 17],
        "exit_gate": [2, 11],
        "tiles": [
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#.E..........................#",
            "####BBBBBB##RRRRRR########...#",
            "#............................#",
            "#............................#",
            "#..........................###",
            "#............................#",
            "#.S..........................#",
            "#####BBBBRRBBBB##RRRRRR#######",
            "##############################",
        ],
        "initial_rules": {},
        "moving_obstacles": [{"type": "orbit",
              "center": [416, 522],
              "radius": 54,
              "count": 2,
              "speed": 2.0,
              "size": 10},
             {"type": "oscillator",
              "rect": [468, 224, 24, 80],
              "axis": "y",
              "distance": 80,
              "period": 2.0,
              "phase": 0.0}],
        "timed_traps": [{"rect": [650, 420, 12, 156], "period": 2.0, "on": 0.9, "offset": 0.0}],
        "rule_change": [{"trigger": {"type": "zone", "rect": [480, 416, 64, 160]},
              "method": "glitch",
              "changes": {"red_meaning": "safe", "blue_meaning": "danger"}},
             {"trigger": {"type": "zone", "rect": [320, 256, 64, 128]},
              "method": "vague_message",
              "message": "again?",
              "changes": {"red_meaning": "danger", "blue_meaning": "safe"}}],
        "moving_platforms": [],
    },
    {
        "id": 13,
        "title": "THE SHORT WAY",
        "concept": "The short path looks safe but hides a late trap. The long way is the real safe way.",
        "instruction": "RED = DANGER   BLUE = SAFE",
        "player_start": [2, 17],
        "exit_gate": [27, 17],
        "tiles": [
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#.............##.............#",
            "#........BB........BB........#",
            "#............................#",
            "#......................##....#",
            "#....##......................#",
            "#............................#",
            "#.S........................E.#",
            "#####LLLLLLLLLLLLLLLLLLLL#####",
            "##############################",
        ],
        "initial_rules": {},
        "moving_obstacles": [{"type": "orbit",
              "center": [544, 352],
              "radius": 50,
              "count": 1,
              "speed": 2.2,
              "size": 10}],
        "timed_traps": [{"rect": [394, 160, 12, 250], "period": 2.2, "on": 1.0, "offset": 0.0}],
        "rule_change": [{"trigger": {"type": "time", "t": 0.4},
              "method": "vague_message",
              "message": "the short way is the smart way.",
              "changes": {}}],
        "moving_platforms": [],
    },
    {
        "id": 14,
        "title": "CONTROLLED CHAOS",
        "concept": "Every 3.5s the rule shuffles from a fixed, playable set. Read the room.",
        "instruction": "RED = DANGER   BLUE = SAFE",
        "player_start": [1, 17],
        "exit_gate": [27, 17],
        "tiles": [
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#..########################..#",
            "#............................#",
            "#............................#",
            "#S.........................E.#",
            "###RRRRR##BBBBB##PPPPP##PBP###",
            "##############################",
        ],
        "initial_rules": {"red_meaning": "danger",
             "blue_meaning": "safe",
             "purple_meaning": "safe",
             "controls_swapped": False},
        "cycle": {"period": 3.5,
             "warn": 0.6,
             "states": [{"changes": {"red_meaning": "danger",
                                     "blue_meaning": "safe",
                                     "purple_meaning": "safe",
                                     "controls_swapped": False},
                         "display": "RED = DANGER   BLUE = SAFE"},
                        {"changes": {"red_meaning": "safe",
                                     "blue_meaning": "danger",
                                     "purple_meaning": "safe",
                                     "controls_swapped": False},
                         "display": "RED = SAFE   BLUE = DANGER"},
                        {"changes": {"red_meaning": "danger",
                                     "blue_meaning": "safe",
                                     "purple_meaning": "danger",
                                     "controls_swapped": True},
                         "display": "RED = DANGER   BLUE = SAFE   ??? = ???"},
                        {"changes": {"red_meaning": "safe",
                                     "blue_meaning": "danger",
                                     "purple_meaning": "danger",
                                     "controls_swapped": False},
                         "display": "RED = SAFE   BLUE = DANGER"}]},
        "moving_obstacles": [],
        "timed_traps": [],
        "moving_platforms": [],
        "rule_change": [],
    },
    {
        "id": 15,
        "title": "COLLAPSE",
        "concept": "Every mechanism at once on one long, fair route. No rule is absolute.",
        "instruction": "RED = DANGER   BLUE = SAFE",
        "player_start": [2, 17],
        "exit_gate": [2, 11],
        "tiles": [
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#............................#",
            "#.........BB.................#",
            "#.E..........................#",
            "########RRRRRR##LLLL######...#",
            "#............................#",
            "#............................#",
            "#..........................###",
            "#............................#",
            "#.S..........................#",
            "####BBB#MMM##RRRR##PPP##BB####",
            "##############################",
        ],
        "initial_rules": {"purple_meaning": "danger"},
        "moving_obstacles": [{"type": "orbit",
              "center": [480, 512],
              "radius": 52,
              "count": 2,
              "speed": 1.8,
              "size": 10},
             {"type": "oscillator",
              "rect": [708, 224, 24, 80],
              "axis": "y",
              "distance": 80,
              "period": 2.0,
              "phase": 0.0}],
        "timed_traps": [{"rect": [138, 256, 12, 128], "period": 2.0, "on": 0.9, "offset": 0.0}],
        "rule_change": [{"trigger": {"type": "zone", "rect": [352, 416, 64, 160]},
              "method": "glitch",
              "pre_glitch": 0.3,
              "changes": {"red_meaning": "safe", "blue_meaning": "danger"}},
             {"trigger": {"type": "zone", "rect": [704, 416, 64, 160]},
              "method": "vague_message",
              "message": "are you sure?",
              "changes": {"controls_swapped": True}},
             {"trigger": {"type": "zone", "rect": [448, 256, 64, 128]},
              "method": "glitch",
              "changes": {"red_meaning": "danger", "blue_meaning": "safe"},
              "display": "RED = SAFE   BLUE = DANGER"}],
        "moving_platforms": [],
    },
]
